config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => { registrations: 'registrations' }
  root 'home#index'
  resources :manners
  resources :people do
    resources :contents
    collection do
      get :search
    end
  end
  
  resources :contents
  
  get '/manners/manner/manner1', to: 'manners#manner1', as: 'manner1'
  get '/manners/manner/manner2', to: 'manners#manner2', as: 'manner2'
  get '/manners/manner/manner3', to: 'manners#manner3', as: 'manner3'
  get '/manners/manner/manner4', to: 'manners#manner4', as: 'manner4'
  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/content.rb
class Content < ApplicationRecord
  belongs_to :person
  belongs_to :user
  # self.per_page = 3
  
  validates :inout, presence: true
  validates :category, presence: true
  validates :date, presence: true
  
end

app/models/manner.rb
class Manner < ApplicationRecord
end

app/models/person.rb
class Person < ApplicationRecord
    has_many :contents, dependent: :destroy
    belongs_to :user
    
    # paginates_per 2
    
    mount_uploader :image, ImageUploader
    
    validates :name, presence: true 
    validates :phone, presence: true 
    
    searchable do
        text :name, :phone, :relation
    end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :people
  has_many :contents
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_action :authenticate_user!
  
  def index
  end
  
  def new
    @person = Person.find(params[:person_id])
  end
  
  def create
    @person = Person.find(params[:person_id])
    @content = @person.contents.new(content_params)
    
    # if @content.inout == '수입'
    #   @person.sum += @content.cost
    # elsif @content.inout == '지출'
    #   @person.sum -= @content.cost     #sum 값의 변경을 허락하지않아서 생김
    # end
    
    # @person.update(params.permit(:sum))
    
    if @content.save()
      redirect_to @person
    else
      redirect_to new_person_content_path
    end
  end
  
  def show
    # @person = Person.find(params[:id])
    # @contents = @person.contents
    # @contents = @person.contents.order("created_at DESC").page(params[:page])
    @person = Person.find(params[:person_id])
    @contents = @person.contents
    # @content = Content.find(params[:id])   #id를 통해서 저장된 값을 찾아서 article이란 변수에 저장 출력
  end
  
  def edit
    @content = Content.find(params[:id])
    @person = Person.find(@content.person_id)
    
    # if @content.inout == '수입'
    #   @person.sum -= @content.cost
    # elsif @content.inout == '지출'
    #   @person.sum += @content.cost     #sum 값의 변경을 허락하지않아서 생김
    # end
    
    # @person.update(params.permit(:sum))
  end
  
  def update
    # @person = Person.find(params[:id])
    # @content = @person.contents.find(params[:content])
    @content = Content.find(params[:id])
    @person = Person.find(@content.person_id)
    
    # if @content.inout == '수입'
    #   @person.sum += @content.cost
    # elsif @content.inout == '지출'
    #   @person.sum -= @content.cost     #sum 값의 변경을 허락하지않아서 생김
    # end
    
    if @content.update(content_params)
      # @person.update(params.permit(:sum))
       redirect_to @person
     else
       redirect_to new_person_content_path(@person)
    end
  end
  
  def destroy
    @content = Content.find(params[:id])
    @person = Person.find(@content.person_id)
    
    # if @content.inout == '수입'
    #   @person.sum -= @content.cost
    # elsif @content.inout == '지출'
    #   @person.sum += @content.cost     #sum 값의 변경을 허락하지않아서 생김
    # end
    # @person.update(params.permit(:sum))
    @content.destroy   #삭제를 해도 할당된 id에 저장된 값은 그대로 유지된다.
    
    redirect_to @person 
  end
  
  
  private
    def content_params
      params.require(:content).permit(:inout, :category, :title, :cost, :memo, :date, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
    end
end

app/controllers/manners_controller.rb
class MannersController < ApplicationController
  
  def new
  end
  
  def create
  end
  
  def index
    @manners = Manner.all
  end
  
  def manner1
  end
  
  def manner2
  end
  
  def manner3
  end
  
  def manner4
  end
  
  def show
  end
    
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
    before_action :authenticate_user!
    
    def new
    end
    
    def index
        @people = Person.all.order(:name)
    end
    
    def create
        @person = Person.new(params.require(:person).permit(:name, :phone, :relation, :user_id, :image))
        
        if @person.save
            redirect_to people_path
        else
            redirect_to new_person_path
        end
    end
    
    def show
        @person = Person.find(params[:id])
        
        # redirect_to person_content_path(@person)
        @contents = @person.contents
        # @contents = @person.contents.paginate(:page => params[:page], :per_page => 5)
        # @contents = @person.contents.order("created_at DESC").page(params[:page])
        
        @person.contents.each do |content|
          if content.inout == '수입'
            @person.sum += content.cost
          elsif content.inout == '지출'
            @person.sum -= content.cost
          end
        end
        
        @person.update(params.permit(:sum))
    end
    
    def destroy
        person = Person.find(params[:id])
        person.destroy
        
        redirect_to people_path
    end
    
    def edit
        @person = Person.find(params[:id])
    end
    
    def update
        @person = Person.find(params[:id])
        @person.update(params.require(:person).permit(:name, :phone, :relation, :user_id, :image))
        
        redirect_to people_path
    end
    
    def search
        @people = Person.search do
            fulltext params[:search]
        end.results
        
        if params[:search] == ""
            redirect_to people_path
        else
            respond_to do |format|
                format.html { render :action => "index" }
                format.xml  { render :xml => @people }
            end
        end
    end
    
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
    
  private
  
  def sign_up_params
    params.require(:user).permit(:email, :name, :age, :sex, :password, :password_confirmation)
  end
  
  def account_update_params
    params.require(:user).permit(:email, :name, :age, :sex, :password, :password_confirmation, :current_password)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/manners_helper.rb
module MannersHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/contents/edit.html.erb
<head>
   <link href="https://fonts.googleapis.com/css?family=Nanum+Gothic:400,700&amp;subset=korean" rel="stylesheet">

  <style>
    body.main3{
             font-family: 'Nanum Gothic', sans-serif;
             background: url("/image/wave.jpg");
             background-size: cover;
             color: #D8E6F0;
        }
        
    .field{
      width: 400px;
    }    
        
  </style>
</head>

<body class="main3">
  <center><h2 class="mt-5" style="letter-spacing:-1px;">내역 수정</h2></center>
  <div class='container' style="overflow:scroll; overflow-x:hidden; width:inherit; height: 450px; font-weight: bold; display:flex; justify-content:center; margin-top: 30px; letter-spacing:-1px;">
    <div class="field">

    <%= bootstrap_form_for :content, :html => {:multipart => true, name: "contentForm",  :onsubmit => "return validateform();"}, url: content_path(@content), method: :patch do |f| %>
    
       <!-- 수입 지출 목록 -->
      <%= f.text_field :inout, :label => '수지내역' %>

      <%= f.select(:category, ['결혼식', '장례식', '돌잔치(백일)', '기타'],{:label => '항목',:class => 'my_style_class'})%>
      
      <%= f.text_field :title, :label => '제목'%>
      
      <%= f.text_field :cost, :label => '금액' %>
      
      <%= f.text_area :memo, :label => '메모' %>
      
      <%= f.date_field(:date, {:label => '날짜'}) %>
      
      <div style="text-align:right; padding-top: 10px;">
      <%= f.submit %>
      </div>
    <% end %>
    </div>
  </div>
  
  <script>
    function validateform(){
        var contentInout = document.contentForm.content_inout;
        var contentCategory = document.contentForm.content_categoty;
        var contentDate = document.contentForm.content_date;

        if(contentInout.value==""){
            alert("수입/지출이 선택되지 않았습니다.");
        }
        else if(contentCategory.value==""){
            alert("카테고리가 선택되지 않았습니다.");
        }
        else if(contentDate.value==""){
            alert("날짜가 선택되지 않았습니다.");
        }
    }
  </script>
</body>

app/views/contents/new.html.erb
<head>
 <link href="https://fonts.googleapis.com/css?family=Nanum+Gothic:400,700&amp;subset=korean" rel="stylesheet">
  
  <style>
  
    body.main5 {
    
      font-family: 'Nanum Gothic', sans-serif;
      background: url("/image/wave.jpg");
      background-size: cover;
      color: #D8E6F0;
         
    }
    
    .field{
      width: 400px;
    }
    
    .btn-three {
    color: #FFF;
    transition: all 0.5s;
    position: relative;
    }
    
    .btn-three::before {
        content: '';
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        z-index: 1;
        background-color: rgba(255,255,255,0.1);
        transition: all 0.3s;
    }
    
    .btn-three:hover::before {
        opacity: 0 ;
        transform: scale(0.5,0.5);
    }
    
    .btn-three::after {
        content: '';
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        z-index: 1;
        opacity: 0;
        transition: all 0.3s;
        border: 1px solid rgba(255,255,255,0.5);
        transform: scale(1.2,1.2);
    }
    
    .btn-three:hover::after {
        opacity: 1;
        transform: scale(1,1);
    }
  
  </style>
</head>

<body class="main5">
  <center><h2 class="mt-5" style = "letter-spacing:-1px;">내역 추가</h2></center>
  <div class='container' style="overflow:scroll; overflow-x:hidden; width:inherit; height: 450px; font-weight: bold; display:flex; justify-content:center; margin-top: 30px; letter-spacing:-1px;">
     
  <!--style="display:flex; justify-content:center; margin-top: 50px; ">-->
    
    <div class ="field">

    <%= bootstrap_form_for :content, :html => {:multipart => true, name: "contentForm",  :onsubmit => "return validateform();"}, url: person_contents_path(@person.id) do |f| %>
      
      <%= f.select(:inout, ['선택', '수입', '지출'], {:label => '수지내역', :class => 'my-style_class'}) %>
 
      <%= f.select(:category, ['선택', '결혼식', '장례식', '돌잔치(백일)', '기타'], {:label => '항목', :class => 'my_style_class'})%><br>
      
      <%= f.text_field :title, :label => '제목' %><br>

      <%= f.number_field :cost, :label => '비용', step: 10000 %><br>

      <%= f.text_area :memo, :label => '메모' %><br>

      <%= f.date_field(:date, :label => '날짜') %>
      
      <div style="text-align:right;"> 
        <%= f.button :추가, label: '추가', class: 'btn btn-three', style: 'margin-top: 20px;' %>
      </div>
    <% end %>
    </div>
  </div>
  
  <script>
    function validateform(){
        var contentInout = document.contentForm.content_inout;
        var contentCategory = document.contentForm.content_category;
        var contentDate = document.contentForm.content_date;
        var contentCost = document.contentForm.content_cost;

        if(contentInout.value==""){
            alert("수입/지출이 선택되지 않았습니다.");
            return false;
        }
        else if(contentCategory.value==""){
            alert("카테고리가 선택되지 않았습니다.");
            return false;
        }
        else if(contentDate.value==""){
            alert("날짜가 선택되지 않았습니다.");
            return false;
        }
        else if(contentCost.value==""){
            alert("금액이 입력되지 않았습니다.");
            return false;
        }
    }
  </script>
</body>

app/views/home/index.html.erb
<html>
    
<head>
     <link href="https://fonts.googleapis.com/css?family=Nanum+Myeongjo:400,700,800&amp;subset=korean" rel="stylesheet">
     <link href="/app/assets/stylesheets/home.scss" rel="stylesheet">
     
    <style>
    
    p {
        width: 400px;  
        background-color: rgba(255, 255, 255, 0.1);
        padding: 5px;
    }
    
    .login
    {
        padding-top: 50px;
        height: stretch;
        text-align: center;
        font-weight: bold;
        font-size: 1.6em;
        letter-spacing:-3px;
        font-family: 'Cinzel', serif;
        color: white;
        justify-content:center;
    }
   
      body {
           margin : 0;
           padding : 0;
           background-color:black;
          
        }
     
        video {
         position: fixed;
         top: 50%; left: 50%;
         min-width: 100%;
         min-height: 100%;
         width: auto;
         height: auto;
         transform: translate(-50%, -50%);
         opacity: 0.7;
         z-index : -1;
        }

    </style>        
</head>

<body>
   
   <!--<video class="bg_video1" autoplay loop poster = "/image/sky1.jpg">-->
   <!--   <source src = "/video/Sky.mp4" type = "video / mp4"></source>-->
   <!--</video>-->
   <video autoplay muted loop>
      <source src="/video/Sky.mp4" type="video/mp4"></source>
   </video>

<div class="container mt-4 px-5">
            <div class = "login" style="justify-content:center;">
                <% if user_signed_in? %><img src="/image/salary.png" width= "150">
                <div style="display:flex; justify-content:center; width:auto; margin-top: 50px;">
                    <p><%= current_user.name %> 님, <br />안녕하세요!</p>
                    </div>
                <% else %><img src="/image/message (1).png" width="150">
                <div style="display:flex; justify-content:center; width:auto; margin-top:25px;">
                    <p>로그인이<br />필요합니다.</p>
                </div>
                <% end %>
            </div>
            <!--<p style="text-align: center;"></p>-->
</div>
        
        
</body>

</html>

app/views/people/edit.html.erb
<html>
<head>
     <link href="https://fonts.googleapis.com/css?family=Nanum+Gothic:400,700&amp;subset=korean" rel="stylesheet">

    <style>
    
    .info_edit{
        width:400px; 
        font-weight: bold;
        line-height: 100%;
    }
    
    body.main6{
        
      font-family: 'Nanum Gothic', sans-serif;
      background: url("/image/wave.jpg");
      background-size: cover;
      color: #D8E6F0;
    }
    
    </style>
    
</head>

<body class="main6">
<div class="container" style="font-weight: bold; display:flex; justify-content:center; margin-top: 50px; letter-spacing:-1px;">
      <div class="info_edit">
    <center><h2>연락처 수정</h2></center>
    <%= form_for :person, :html => { :multipart => true, name: "personForm", :onsubmit => "return validateform();"}, url: person_path, method: :patch  do |f| %>
        <div class="field" style="padding-top: 30px;">
            <p>프로필 사진</p>
            <%= f.file_field :image %>
        </div>
        <br><br>
        <div class="field">
            <p>이름</p>
            <%= f.text_field :name , class: 'form-control' %>
        </div>
        <br><br>
        <div class="field">
            <p>전화번호</p>
            <%= f.text_field :phone , class: 'form-control' %>
        </div>
        <br><br>
        <div class="field">
            <p>관계</p></p>
            <%= f.select(:relation, ['가족', '친구', '지인', '직장동료', '거래처', '기타'],{:class => 'input-group'})%>
        </div>
        
    
        <%= f.hidden_field :user_id, value: current_user.id %>
        <br><br>
        <p style="text-align:right;"><%= f.button :변경, label: '등록' , class: 'btn btn-outline-dark' %></p>
    <% end %>
    </div>
</div>
</body>


<script>
        function validateform(){
            var personName = document.personForm.person_name;
            var personPhone = document.personForm.person_phone;
            var personImage = document.personForm.person_image;

            if(personName.value==""){
                alert("이름이 입력되지 않았습니다.");
                document.personForm.person_name.focus();
                document.getElementById('person_name').select();
                return false;
            }
            else if(personName.value.length > 5){
                alert("이름은 5글자 이하로 작성해주세요.");
                document.personForm.person_name.focus();
                document.getElementById('person_name').select();
                return false;
            }
            else if(personPhone.value==""){
                alert("전화번호가 입력되지 않았습니다.");
                document.personForm.person_phone.focus();
                document.getElementById('person_phone').select();
                return false;
            }
        }
</script>

</html>

app/views/people/index.html.erb
<head>
     <link href="https://fonts.googleapis.com/css?family=East+Sea+Dokdo&amp;subset=korean" rel="stylesheet">
     <link href="https://fonts.googleapis.com/css?family=Nanum+Gothic:400,700&amp;subset=korean" rel="stylesheet">
     <link href="https://fonts.googleapis.com/css?family=Black+Han+Sans&amp;subset=korean" rel="stylesheet">
     <link href="https://fonts.googleapis.com/css?family=Do+Hyeon&amp;subset=korean" rel="stylesheet">
     <link href="/app/assets/stylesheets/button.scss" rel="stylesheet">
     
     <style>

    .card{
          background-color:rgba(255,255,255,0.1);
          border: solid 1px #D8E6F0;
        }
        
    .name_search{
             border: none;
             border-bottom: solid 0.5px black;
             margin-bottom: 20px;
    }   
         

    body.main{
        background: url("/image/wave.jpg");
        background-size: cover;
    }
        
            .btn-three {
            color: #FFF;
            transition: all 0.5s;
            position: relative;
        }
        .btn-three::before {
            content: '';
            position: absolute;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            z-index: 1;
            background-color: rgba(255,255,255,0.1);
            transition: all 0.3s;
        }
        .btn-three:hover::before {
            opacity: 0 ;
            transform: scale(0.5,0.5);
        }
        
        .btn-three::after {
            content: '';
            position: absolute;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            z-index: 1;
            opacity: 0;
            transition: all 0.3s;
            border: 1px solid rgba(255,255,255,0.5);
            transform: scale(1.2,1.2);
        }
        
    .btn-three:hover::after {
            opacity: 1;
            transform: scale(1,1);
    }
        
    input, span.input_span, label {
        display: block;
        margin: 10px;
        padding: 5px;
        border: none;
        font-size: 20px;
    }
    
    input:focus {
        outline: 0;
    }
        
    input.question {
        font-size: 20px;
        font-weight: 300;
        border-radius: 2px;
        margin: 0;
        border: none;
        width: 30%;
        background: rgba(0, 0, 0, 0);
        transition: padding-top 0.2s ease, margin-top 0.2s ease;
        overflow-x: hidden;
    }
    
    input.question+label {
        display: block;
        position: relative;
        white-space: nowrap;
        padding: 0;
        margin: 0;
        width: 13%;
        border: 0.5px solid white;
        transition: width 0.4s ease;
        height: 0px;
    }
    
    input.question:focus+label {
      width: 20%;
    }
    
    input.question:focus,
    input.question:valid {
      padding-top: 33px;
    }
    
    input.question:focus+label>span.input_span,
    input.question:valid+label>span.input_span {
      top: -78px;
      font-size: 22px;
      color: white;
    }
    
    input.question:valid+label {
      border: solid 0.3px yellow;
      transition: appear 2s ease;
    }
    
    input.question:invalid {
      box-shadow: none;
    }
    
    input.question+label>span.input_span {
      margin: 0;
      position: absolute;
      color: white;
      font-size: 30px;
      top: -50px;
      left: 0px;
      z-index:-1;
      transition: top 0.2s ease, font-size 0.2s ease, color 0.2s ease;
    }
    
    input[type="submit"] {
      transition: opacity 0.2s ease, background 0.2s ease;
      display: block;
      opacity: 0;
      margin: 10px 0 0 0;
      padding: 10px;
      cursor: pointer;
    }
    
    input[type="submit"]:hover {
      background: #eee;
    }
    
    input[type="submit"]:active {
      background: #999;
    }
    
    input.question:invalid ~ input[type="submit"]{
      display: none;
    }
    
    input.question:valid ~ input[type="submit"]{
      animation: appear 2s forwards;
    }
    
    select:invalid ~ input[type="submit"]{
        display:none;
    }
    
    select:valid ~ input[type="submit"]{
        animation: appear 2s forwards;
    }
    
    @-webkit-keyframes appear {
      100% {
        opacity: 1;
      }
    }
    
    @keyframes appear {
      100% {
        opacity: 1;
      }
    }
    
    </style>
</head>

<body class="main">
  <div class="container">
      <%= link_to new_person_path do %>
          <div class="box-3">
            <div class="btn btn-three">
              <span>연락처 추가</span>
            </div>
          </div>
      <% end %><br>
  
      <div>
          <%= form_tag search_people_path, :method => :get do %>
              <%= text_field_tag :search, nil, :class => 'question', :required => 'true' , :autocomplete => 'off' %>
                  <label for="search"><span class="input_span">이름 검색</span></label>
              <%= submit_tag "검색", :id => 'search', :name => nil  %>
          <% end %>
          
          <%= form_tag search_people_path, :method => :get do %>
              <%= select_tag :search, options_for_select([ "관계", "가족", "친구", "지인", "직장동료", "거래처", " 기타" ]) %>
              <%= submit_tag "검색", :name => nil %>
          <% end %>
      </div>
      
      <div class="row">
          <% @people.each do |person| %>
              <% if(person.user_id == current_user.id) %>
              <div class="col-6 col-sm-4 col-md-3 col-lg-2 pt-2">
                  <div class="card" style="width: 10rem; height: 330px; margin:10px;">
                      <center><%= image_tag person.image.url, class: 'custom_img'%></center>
                        <div class="card-body">
                          <center>
                              <h5 class="card-title" style="color: #D8E6F0; font-family: 'Black Han Sans', sans-serif; font-size:2em;"><%= person.name %></h5>
                              <p class="card-text"style="color: white; font-weight: bold; font-family: 'Nanum Gothic', sans-serif;line-height: 8px"><%= person.relation %></p>
                              <p class="card-text"style="color: white; font-weight: bold; font-family: 'Nanum Gothic', sans-serif;line-height: 8px"><%= person.phone %></p>
                              
                              <%= link_to person_path(person) do %>
                                  <div class="box-3"> 
                                    <div class="btn btn-three" style="margin-top:5px;">
                                      <span>내용 상세</span>
                                    </div>
                                  </div>                            
                              <% end %>
                          </center>
                      </div>
                  </div>
              </div>
            <% end %>
        <% end %>
    </div>
  </div>
</body>

app/views/people/show.html.erb
<head>
     <link href="https://fonts.googleapis.com/css?family=East+Sea+Dokdo&amp;subset=korean" rel="stylesheet">
     <link href="https://fonts.googleapis.com/css?family=Nanum+Gothic:400,700&amp;subset=korean" rel="stylesheet">
     <link href="https://fonts.googleapis.com/css?family=Black+Han+Sans&amp;subset=korean" rel="stylesheet">
  <style>
  
    body.main2{
        background: url("/image/wave.jpg");
        background-size: cover;
    }
    
    .card{
      background-color:rgba(255,255,255,0.1);
      border: solid 1px #D8E6F0;
    }
    
    .btn-three {
    color: #FFF;
    transition: all 0.5s;
    position: relative;
    }
    
    .btn-three::before {
        content: '';
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        z-index: 1;
        background-color: rgba(255,255,255,0.1);
        transition: all 0.3s;
    }
    
    .btn-three:hover::before {
        opacity: 0 ;
        transform: scale(0.5,0.5);
    }
    
    .btn-three::after {
        content: '';
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        z-index: 1;
        opacity: 0;
        transition: all 0.3s;
        border: 1px solid rgba(255,255,255,0.5);
        transform: scale(1.2,1.2);
    }
    
    .btn-three:hover::after {
        opacity: 1;
        transform: scale(1,1);
    }
    
  </style>
</head>

<body class="main2">
  <div class="container">
    <div class="row">
      <div class="col-3">
        
        <div class="col-sm">
          <div class="card" style="width: 15rem;">
            <center>
              <%= image_tag @person.image.url, class: 'custom_img'%>
              <div class="card-body">
                  <h5 class="card-title" style="color: #D8E6F0; font-family: 'Black Han Sans', sans-serif; font-size:2em;"><%= @person.name %></h5>
                  <p class="card-text" style="color: white; font-weight: bold; font-family: 'Nanum Gothic', sans-serif;line-height: 8px"><%= @person.relation %></p>
                  <p class="card-text" style="color: white; font-weight: bold; font-family: 'Nanum Gothic', sans-serif;line-height: 8px; padding-bottom: 7px;"><%= @person.phone %></p>
                  <%= link_to image_tag('/image/edit.png', width: '25px', hspace:'20'), edit_person_path(@person) %>
                    
                  
                  <%= link_to image_tag('/image/garbage.png', width: '25px', hspace: '20'), person_path(@person), method: :delete %>
                  
                  
              </div>
            </center>
          </div>
        </div>
      </div>
      
      <div class="col-9">
        <div style="text-align:right; font-weight: bold; font-family: 'Nanum Myeongjo', serif; margin-bottom:12px;">
          <p style="color: #ffffff;"><img src="/image/coins.png" width="30" height="30">
           * 누적금액: 
          <%= @person.sum %>원 * 
          <img src="/image/coins.png" width="30" height="30"></p>
        </div>
        <table class="table table-hover" style=" line-height: 20px">
          <thead>
            <tr style="background-color: rgba(255, 255, 255, 0.05); color: #D8E6F0; font-family: 'East Sea Dokdo', cursive; font-size: 2em;">
              <th>수지</th>
              <th>항목</th>
              <th>제목</th>
              <th>금액</th>
              <th>메모</th>
              <th>날짜</th>
              <th>수정</th>
              <th>삭제</th>
            </tr>
          </thead>
          <tbody>
            <% @contents.each do |content| %>
              <tr style="color: white; font-family: 'Nanum Gothic', sans-serif; letter-spacing: -1px;">
               <td><%= content.inout %></td>
               <td><%= content.category %></td>
               <td><%= content.title %></td>
               <td><%= content.cost %></td>
               <td><%= content.memo %></td>
               <td><%= content.date %></td>
               <td><%= link_to image_tag('/image/edit.png', width: '20px'), edit_content_path(content) %></td>
               <td><%= link_to image_tag('/image/garbage.png', width: '20px'), content_path(content), method: :delete  %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
          <%= link_to new_person_content_path(@person) do %>
            <div class="box-3">
              <div class="btn btn-three">
              <span>내역 추가</span>
              </div>
            </div>
          <%end%>
      </div>
  </div>

</body>